name: Android CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      LOCAL_PROPERTIES_CONTENTS: ${{ secrets.LOCAL_PROPERTIES_CONTENTS }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create local.properties
      run: |
        echo "$LOCAL_PROPERTIES_CONTENTS" > local.properties

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Prod Release AAB
      id: buildRelease
      run: ./gradlew bundleProdRelease

    - name: Verify AAB file exists
      run: |
        if [ ! -f app/build/outputs/bundle/prodRelease/app-prod-release.aab ]; then
          echo "Error: AAB file not found!"
          exit 1
        fi

    - name: Sign AAB
      id: sign
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/prodRelease
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Create service_account.json
      id: createServiceAccount
      run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

    - name: Deploy to Play Store (BETA)
      id: deploy
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: service_account.json
        packageName: com.easyhz.noffice
        releaseFiles: app/build/outputs/bundle/prodRelease/app-prod-release.aab
        track: beta
        whatsNewDirectory: whatsnew/
